source 'https://rubygems.org'
ruby '2.1.1'

gem 'bitters'
gem 'neat'
gem 'rake'
gem 'slim'

gem 'middleman'
gem 'middleman-blog'
gem 'middleman-deploy'
gem 'middleman-imageoptim'
gem 'middleman-livereload'
gem 'middleman-minify-html'
gem 'middleman-syntax'
